from build_tools import *

pwd = PresentDir()
src = Glob('*.c') + Glob('*.cpp')
CPPPATH = [pwd + '/../../include/termios']

group = AddCodeGroup('termios', src,
    depend = ['OS_USING_LIBC_ADAPTER', 'OS_USING_POSIX', 'OS_USING_POSIX_TERMIOS'], 
    CPPPATH = CPPPATH)

Return('group')
