import os
import osconfig
from build_tools import *



pwd = PresentDir()

# add general drivers
src = Split('''
board.c
bsp/bsp.c
''')

# path   include path in project
path =  [pwd,pwd + '/bsp']


if osconfig.CROSS_TOOL == 'gcc':
    src += [pwd + '/startup/startup_mm32f327x_gcc.s']
elif osconfig.CROSS_TOOL == 'keil':
    src += [pwd + '/startup/startup_mm32f327x_arm.s']
elif osconfig.CROSS_TOOL == 'iar':
    src += [pwd + '/startup/startup_mm32f327x_iar.s']

CPPDEFINES = ['MM32F3277','USE_STDPERIPH_DRIVER'] 
group = AddCodeGroup('bsp', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
