Import('OS_ROOT')
Import('osconfig')
from build_tools import *

pwd = PresentDir()

# add the general drivers.
src = Split("""
""")

if IsDefined(['OS_USING_PIN']):
    src += ['drv_gpio.c']
    
if IsDefined(['OS_USING_SERIAL']):
    src += ['drv_usart.c']
    
if IsDefined(['OS_USING_RTC']):
    src += ['drv_rtc.c']

if IsDefined(['OS_USING_SDIO']):
    src += ['drv_sd.c']
    src += ['sdio_sdcard.c']
    

src += ['drv_common.c']

path =  [pwd]

group = AddCodeGroup('hal/drivers', src, depend = ['SERIES_MM32F327X'], CPPPATH = path)

Return('group')
