Import('OS_ROOT')
Import('osconfig')
from build_tools import *

pwd = PresentDir()

src = ['mm32_devices.c']

path =  [pwd]

group = AddCodeGroup('hal/devices', src, depend = ['SERIES_MM32F327X'], CPPPATH = path)
group = AddCodeGroup('hal/devices', src, depend = ['SERIES_MM32L3'], CPPPATH = path)

Return('group')
