Import('OS_ROOT')
Import('osconfig')
from build_tools import *

pwd = PresentDir()
path =  [pwd]
src = []

if IsDefined('OS_USING_ONETLS'):
    # add general drivers
    src += Glob('source/*.c')

    # path   include path in project
    path += [pwd + '/include']
    path += [pwd + '/source']

group = AddCodeGroup('onetls/tls', src, depend = ['OS_USING_ONETLS'], CPPPATH = path)

Return('group')
